version: '3.8'
services:
  stats-server:
    build: ./stats-server
    image: stats-server
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_MONGO_HOST=stats-db
      - DB_MONGO_PORT=27017

  stats-db:
    image: mongo:6.0
    container_name: ewm-stats-mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: stats
    volumes:
      - /var/lib/db/data/stats

  mongo-express:
    image: mongo-express
    container_name: ewm-stats-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:root@stats-db:27017/?authSource=admin

  ewm-service:
    build: ./ewm-service
    image: emw-service
    container_name: ewm-service
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - DB_NAME=emw
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/db/data/main